name: Flask CI Pipeline

on:
  push:
    branches:
      - main  # Trigger CI on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger CI on PRs to the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest  # Runs on the latest version of Ubuntu

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # You can adjust the Python version as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies listed in requirements.txt

    - name: Run tests with pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q  # Run tests, limit to 1 failure, disable warnings

