name: Flask CI Pipeline

on:
  push:
    branches:
      - main  # Trigger CI on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger CI on PRs to the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest  # Runs on the latest version of Ubuntu

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Print directory contents (Debugging Step)
      run: |
        ls -la
    - name: Navigate to project1 directory
      run: cd project1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # You can adjust the Python version as needed

    - name: Install dependencies
      run: |
        pip install Flask==2.2.2
        pip install Werkzeug==2.2.2
        pip install pytest
        pip install -r project1/requirements.txt  # Adjusted path to requirements.txt 

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
          docker build -t flask-app ./project1

    - name: Push Docker image to Docker Hub
      run: |
          docker tag flask-app ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

    - name: Run tests with pytest
      run: |
          docker run flask-app pytest --maxfail=1 --disable-warnings -q

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx
